### ISSUE TITLE
Map all grey (intermittent)

### ISSUE THREAD

**Issue by willnwhite** [MapBBCode/share.mapbbcode.org#37]
The map isn't loading (it's all grey). This happened once before, on the 8th November 2014.

**Comment by Zverik** [comment]
Thanks for the report, the problem seems to be in the specific layer, MapSurfer. It will be fixed later today, I hope. Until then you can use other layers, like "OpenStreetMap".

**Comment by willnwhite** [comment]
Thank you for the tip.

**Comment by Zverik** [comment]
The layer was fixed yesterday. Sorry for inconvenience.

**Comment by willnwhite** [comment]
MapSurfer grey again this morning, other layers working. I'm guessing you meant this is something you don't have control over?
