### ISSUE TITLE
Add mapbbcode to export formats

### ISSUE THREAD

**Issue by unxed** [MapBBCode/share.mapbbcode.org#54]
No ability to get mapbbcode from share.mapbbcode.org. Nonsence!

**Comment by Zverik** [comment]
Press "Edit Raw" and copy the code :)

**Comment by unxed** [comment]
I see only "Fork", "Create new", "Export", layers list and "Sign in".
Where to press?

**Comment by Zverik** [comment]
"Fork"

**Comment by unxed** [comment]
@Zverik, mecri)
